-- SPRING MVC 실습용
DROP TABLE MYBOARD;

CREATE TABLE MYBOARD(
	MYNO INT AUTO_INCREMENT PRIMARY KEY,
	MYNAME VARCHAR(500) NOT NULL,
	MYTITLE VARCHAR(1000) NOT NULL,
	MYCONTENT VARCHAR(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

SELECT * FROM MYBOARD ORDER BY MYNO DESC;

INSERT INTO MYBOARD VALUES(NULL, "관리자", "SPRING TEST", "금요일", NOW());



-- SPRING MVC LOGIN 실습용
DROP TABLE MYMEMBER;

CREATE TABLE MYMEMBER(
	MEMBERNO INT AUTO_INCREMENT PRIMARY KEY,
	MEMBERID VARCHAR(1000) NOT NULL,
	-- UNIQUE 설정하기에는 설정한 크기가 너무 커서 안된다.
	MEMBERPW VARCHAR(1000) NOT NULL,
	MEMBERNAME VARCHAR(1000) NOT NULL
);

SELECT * FROM MYMEMBER;

INSERT INTO MYMEMBER VALUES(NULL, "ADMIN", "1234", "관리자");



